// Post-`tsc` steps for the vendored engine (unified-MCP spec §2.1).
//
// 1. dist/vendor/package.json — the engine's version.ts reads `../package.json`
//    with createRequire to report its own version + the exact lwk_node pin in
//    wallet_diagnostics. Vendored at dist/vendor/depix-sdk/version.js, that
//    lookup lands on dist/vendor/package.json, which tsc does not emit. Without
//    this file diagnostics silently degrade to "unknown"; with it they report
//    THIS package's version and THIS package's lwk pin, which is the truth.
//
// 2. SideShift affiliate id — the engine reads process.env.SIDESHIFT_AFFILIATE_ID
//    at import time; upstream `bake-affiliate.mjs` replaces the compiled module
//    with a literal so the published SDK performs no runtime env read. Mirrored
//    here but ONLY when the env is set and non-empty: baking an empty string
//    would DELETE the runtime env read and leave wallet_shift_usdt permanently
//    broken for an operator who does set the variable. So: env set -> bake
//    (publish builds), env unset -> leave the runtime read (dev + npx builds).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(repoRoot, "dist");
if (!existsSync(dist)) {
  console.error("[postbuild] dist/ not found — run `tsc -p tsconfig.build.json` first (npm run build does).");
  process.exit(1);
}

const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
const manifestDir = join(dist, "vendor");
mkdirSync(manifestDir, { recursive: true });
writeFileSync(
  join(manifestDir, "package.json"),
  JSON.stringify(
    {
      name: `${pkg.name}-vendored-engine`,
      version: pkg.version,
      private: true,
      type: "module",
      dependencies: pkg.dependencies,
      _comment: "Generated by scripts/postbuild.mjs. Read by the vendored engine's version.ts (createRequire('../package.json')) so wallet_diagnostics reports this package's version and lwk_node pin.",
    },
    null,
    2,
  ) + "\n",
);

const affiliate = process.env.SIDESHIFT_AFFILIATE_ID;
const affiliateTarget = join(dist, "vendor", "depix-sdk", "convert", "sideshift-affiliate.js");
if (affiliate && affiliate.length > 0) {
  if (!existsSync(affiliateTarget)) {
    console.error(`[postbuild] ${affiliateTarget} not found — the vendored engine did not compile.`);
    process.exit(1);
  }
  writeFileSync(affiliateTarget, `export const SIDESHIFT_AFFILIATE_ID = ${JSON.stringify(affiliate)};\n`);
  console.log("[postbuild] baked SIDESHIFT_AFFILIATE_ID into the compiled engine.");
} else {
  console.log("[postbuild] SIDESHIFT_AFFILIATE_ID unset — the compiled engine keeps its runtime env read.");
}

console.log("[postbuild] wrote dist/vendor/package.json.");
